# Generated by Django 2.2.10 on 2020-03-09 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200307_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
    ]
