# Generated by Django 2.1.5 on 2020-03-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200307_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Friend',
        ),
        migrations.RemoveField(
            model_name='user',
            name='displayName',
        ),
    ]
