# Generated by Django 2.1.5 on 2020-03-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200310_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='published',
        ),
    ]
