# Generated by Django 2.1.7 on 2020-03-12 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated']},
        ),
    ]
