# Generated by Django 2.2.10 on 2020-03-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200312_2152'),
        ('api', '0007_comment_contenttype'),
    ]

    operations = [
    ]
