# Generated by Django 2.1.5 on 2020-03-21 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20200313_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('host', models.URLField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['published']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published']},
        ),
    ]
