# Generated by Django 2.2.10 on 2020-03-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200321_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='username',
        ),
    ]
