# Generated by Django 2.2.10 on 2020-03-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_node_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='host',
        ),
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='default', max_length=40, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.UUIDField(),
        ),
    ]
