# Generated by Django 2.2.10 on 2020-03-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200324_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(max_length=40),
        ),
    ]
