# Generated by Django 2.1.7 on 2020-03-24 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200324_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('host', models.URLField(max_length=255, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.CreateModel(
            name='LocalLogin',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Login')),
            ],
            bases=('api.login',),
        ),
        migrations.CreateModel(
            name='RemoteLogin',
            fields=[
                ('login_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Login')),
            ],
            bases=('api.login',),
        ),
    ]
