# Generated by Django 2.1.7 on 2020-03-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200324_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(default='crap', max_length=20),
            preserve_default=False,
        ),
    ]
