# Generated by Django 2.1.7 on 2020-03-24 04:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_user_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=django_mysql.models.ListCharField(models.CharField(max_length=40), default=['adasf'], max_length=10, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='github',
            field=models.CharField(max_length=255),
        ),
    ]
