# Generated by Django 2.2.10 on 2020-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_post_visibleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(default='http://glacial-earth-37816.herokuapp.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(default='http://glacial-earth-37816.herokuapp.com/', max_length=255),
        ),
    ]
