# Generated by Django 2.2.10 on 2020-03-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200324_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='local',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='local',
            field=models.BooleanField(default=True),
        ),
    ]
