# Generated by Django 2.2.10 on 2020-03-25 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200313_2303'),
        ('api', '0021_auto_20200325_2017'),
    ]

    operations = [
    ]
