# Generated by Django 2.2.10 on 2020-03-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_merge_20200325_2045'),
        ('api', '0022_merge_20200325_2051'),
    ]

    operations = [
    ]
