# Generated by Django 2.2.10 on 2020-03-27 20:59

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200327_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=django_mysql.models.ListTextField(models.CharField(max_length=63), size=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='visibleTo',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), size=None),
        ),
    ]
