# Generated by Django 2.2.10 on 2020-03-27 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20200327_1737'),
        ('api', '0024_auto_20200327_1726'),
    ]

    operations = [
    ]
