# Generated by Django 2.1.7 on 2020-03-27 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20200327_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='local',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='host',
            field=models.URLField(default='http://glacial-earth-37816.herokuapp.com/', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(default='http://glacial-earth-37816.herokuapp.com/', max_length=255),
        ),
    ]
