# Generated by Django 2.2.10 on 2020-04-05 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200327_2222'),
        ('api', '0025_merge_20200327_2122'),
    ]

    operations = [
    ]
