# Generated by Django 2.2.10 on 2020-04-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200329_1719'),
        ('api', '0027_merge_20200405_0454'),
    ]

    operations = [
    ]
